name: print-name

on: push

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print-name
        run: echo "work_flow_hellow_world"

